---
- name: CFME | Subscribe Using Activation Key | Include Tasks for Installing Custom Facts
  import_role: 
    name: install_custom_facts

- name: CFME | Subscribe Using Activation Key | Re-register Host With New Satellite 6 Activation Key
  redhat_subscription:
    state: present
    org_id: "{{ sat6_org_id }}"
    activationkey: "{{ sat6_activation_key }}"
    force_register: true
