---
- name: Host Reboot | Set Defaults
  set_fact:
    reboot_only_if_needed: True
  when: reboot_only_if_needed is undefined

- block:
  - name: Host Reboot | Install yum-utils
    package:
      name: yum-utils
      state: present

  - name: Host Reboot | Detect if reboot is required
    command: needs-restarting --reboothint
    register: needs_restart_result
    failed_when: needs_restart_result.rc > 1
    changed_when: needs_restart_result.rc == 1
  when: reboot_only_if_needed

- name: Host Reboot | Schedule Reboot
  reboot: 
    post_reboot_delay: "{{ host_post_reboot_delay | default(65) }}"
    reboot_timeout: "{{ host_reboot_timeout | default(600) }}"
  when: needs_restart_result.changed or not reboot_only_if_needed