---
# tasks file for install_custom_facts

- name: CFME | Install Custom Facts | Create /etc/ansible/facts.d
  file:
    state: directory
    recurse: True
    path: /etc/ansible/facts.d

- name: CFME | Install Custom Facts | Install Fact
  copy:
    src: cfme.fact
    dest: /etc/ansible/facts.d/
    mode: 0755
  register: cfme_install_custom_facts_result

- name: CFME | Install Custom Facts | Gather New Facts
  setup:
  when: cfme_install_custom_facts_result is changed
  