---
- name: CFME | Install Custom Facts
  hosts: cfme
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Install Custom Facts | Include Tasks
      import_role:
        name: install_custom_facts

        
